### ISSUE TITLE
Can't install ISP in the WSL2.

### ISSUE THREAD

**Issue by ZiguoFu** [ProjectISP/ISP#11]
I have created a virtual environment by typing "conda create --name isp python=3.8" in my WSL2 with Ubuntu 20.4.

I have already installed VcXsrv.

In the environment isp, I have installed all the requirements except the mtspec which was installed unsuccessfully by typing "pip install mtspect" under python 3.8.

I go to ./ISP/install and type:  ./ISP_installer.sh, but it does not work as shown below:

![QQ截图20221218164438](https://user-images.githubusercontent.com/68380266/208289928-60523553-b49f-4cf7-aaee-8dd45b7ab99d.png)

**Comment by jmarinroa** [comment]
Hello ZiguoFu,
Delete the isp virtual environment you created, the ISP installer will create a new one.
Then try installing ISP by following the steps at: https://projectisp.github.io/ISP_tutorial.github.io/install/#installation
In the attached document you will find some more information related to the installation using WSL. 

[Running_WSL_GUI_ Apps_and_install_ISP_on_W10_v2.pdf](https://github.com/ProjectISP/ISP/files/10254486/Running_WSL_GUI_.Apps_and_install_ISP_on_W10_v2.pdf)

**Comment by ZiguoFu** [comment]
Dear jmarinroa,
Thanks for your help! Acccording to your detailed guidance, I have successfully run ISP at my WSL2 terminal. Thank you again!

**Comment by jmarinroa** [comment]
You're welcome,  ZiguoFu
