### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'get_coordinates' []

### ISSUE THREAD

**Issue by wangzb0329** [ProjectISP/ISP#5]
Dear ISP team,
I meet this error when I import the metadata at the moment tensor inversion module: 
AttributeError: 'dict' object has no attribute 'get_coordinates' []. 
Maybe there is an error in my stationxml file so that the module can't extract the station's coordinates, how can l do with it?
Here is my stationxml file.
[stations.xml.zip](https://github.com/ProjectISP/ISP/files/8469427/stations.xml.zip)
Could you give me some suggestions?
Thank you

**Comment by rcabdia** [comment]
We are working on your issue, I will answer you very soon!

Many thanks for trust on ISP

**Comment by jrelinquem** [comment]
Hi

Internally, our software uses obspy read_inventory function to read the metadata file. It seems that this function needs that every station has a Site element with the name of the place where the station is located. 

I have modified your metadata to add the Site elements at every station and now it seems to work.
[stations_with_sites.zip](https://github.com/ProjectISP/ISP/files/8476370/stations_with_sites.zip)

If you see at the modified metadata, for example at CQ.ROC station, there is:
<Site>
  <Name> Rochester, New York, U.S.A. </Name>
<Site>

Please, let us know if this solves your issue, and thanks again for trusting on ISP.

**Comment by wangzb0329** [comment]
I can run it successfully based on your suggestion. Thank you!

**Comment by wangzb0329** [comment]
Hi
When I run the module, I encountered a bug in the results of Histograms—uncertainty of MT parameters.  The DC-part corresponds to the station map, Here is the screenshot.
<img width="530" alt="截屏2022-04-13 上午10 18 25" src="https://user-images.githubusercontent.com/54739388/163089411-579cb47b-9d8b-4fd9-82c7-96889ae9b12f.png">

**Comment by rcabdia** [comment]
Many thanks for your point, Jiri is already working in ISP 2.0 improving MTI functionality and plotting presentation.

Hope we have ISP2.0 ready soon !!

**Comment by wangzb0329** [comment]
Wish everything fine with your work！
